# Generated by Django 4.1.1 on 2022-10-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('texto', models.CharField(max_length=300)),
                ('contacto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('texto', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=300)),
                ('link_texto', models.URLField(max_length=70)),
                ('link_url', models.URLField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='IterAnteriores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('texto', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartel', models.FileField(upload_to='base/')),
                ('titulo', models.CharField(max_length=40)),
                ('pie_texto', models.CharField(max_length=40)),
                ('link_texto', models.CharField(max_length=40)),
                ('link_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('poster', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion_titulo', models.CharField(max_length=40)),
                ('resp_nombre', models.CharField(max_length=20)),
                ('resp_apellido_pat', models.CharField(max_length=20)),
                ('resp_apellido_mat', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('institucion', models.CharField(max_length=40)),
                ('departamento', models.CharField(max_length=40)),
                ('grado', models.CharField(max_length=30)),
                ('modalidad', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=70)),
                ('autores', models.CharField(max_length=300)),
                ('resumen', models.FileField(upload_to='registros/resumenes/')),
                ('constancia', models.FileField(upload_to='registros/constanciaas/')),
                ('estatus', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('pdf', models.FileField(upload_to='programa/')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('mensaje', models.CharField(max_length=300)),
                ('link_resumen', models.FileField(upload_to='registros/resumenes/')),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('texto', models.CharField(max_length=300)),
                ('widget', models.URLField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=70)),
                ('plantilla_constancias', models.FileField(upload_to='constancias/base/')),
                ('correo_comunicacion', models.EmailField(max_length=254)),
                ('correo_contrasena', models.CharField(max_length=100)),
                ('anteriores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.iteranteriores')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.plantillabase')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.contacto')),
                ('inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.inicio')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.poster')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.programa')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.registro')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.ubicacion')),
            ],
        ),
    ]
