# Generated by Django 4.1.1 on 2022-11-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="editing",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
