# Generated by Django 4.1.1 on 2022-11-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ubicacionpage",
            name="url_maps_embed",
            field=models.URLField(max_length=500),
        ),
    ]
