# Generated by Django 4.1.1 on 2022-11-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="active",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
