# Generated by Django 4.1.1 on 2022-11-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="posterpage", name="title",),
        migrations.RemoveField(model_name="presentacionregistro", name="departamento",),
        migrations.RemoveField(model_name="presentacionregistro", name="institucion",),
        migrations.RemoveField(model_name="programapage", name="title",),
        migrations.AddField(
            model_name="author",
            name="departamento",
            field=models.CharField(default="", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="institucion",
            field=models.CharField(default="", max_length=60),
            preserve_default=False,
        ),
    ]
