# Generated by Django 4.1.1 on 2022-11-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_alter_presentacionregistro_resp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='active',
            field=models.BooleanField(),
        ),
    ]
