# Generated by Django 4.1.1 on 2022-11-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0002_evento_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="ubicacionpage",
            name="url_maps_embed",
            field=models.URLField(default="", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programapage",
            name="programa_pdf",
            field=models.FileField(upload_to="TestApp/static/TestApp/archivos/"),
        ),
        migrations.AlterField(
            model_name="ubicacionpage", name="url_maps", field=models.URLField(),
        ),
    ]
