# Generated by Django 4.1.1 on 2022-11-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0002_alter_ubicacionpage_url_maps_embed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ubicacionpage",
            name="url_maps_embed",
            field=models.CharField(max_length=500),
        ),
    ]
