# Generated by Django 4.1.1 on 2022-11-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0003_alter_ubicacionpage_url_maps_embed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="plantilla_constancias_img",
            field=models.ImageField(
                blank=True, null=True, upload_to="plantilla_constancias/"
            ),
        ),
        migrations.AlterField(
            model_name="posterpage",
            name="poster_img",
            field=models.ImageField(upload_to="poster/"),
        ),
        migrations.AlterField(
            model_name="posterpage",
            name="poster_pdf",
            field=models.FileField(upload_to="poster/"),
        ),
        migrations.AlterField(
            model_name="presentacionregistro",
            name="resumen",
            field=models.FileField(upload_to="resumenes/"),
        ),
        migrations.AlterField(
            model_name="programapage",
            name="programa_img",
            field=models.ImageField(upload_to="programa/"),
        ),
        migrations.AlterField(
            model_name="programapage",
            name="programa_pdf",
            field=models.FileField(upload_to="programa/"),
        ),
        migrations.AlterField(
            model_name="registropage",
            name="formato_resumen_pdf",
            field=models.FileField(upload_to="registro/"),
        ),
    ]
