# Generated by Django 4.1.1 on 2022-11-19 20:13

import TestApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0003_alter_ubicacionpage_url_maps_embed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentacionregistro",
            name="resumen",
            field=models.FileField(
                upload_to="registros/resumenes/",
                validators=[TestApp.models.validate_file_extension_pdf],
            ),
        ),
    ]
