# Generated by Django 4.1.1 on 2022-11-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0003_alter_evento_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacionregistro',
            name='presentacion_titulo',
            field=models.CharField(max_length=40, verbose_name='Título de la presentación'),
        ),
    ]
