# Generated by Django 4.1.1 on 2022-11-19 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0004_alter_presentacionregistro_resumen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentacionregistro",
            name="resumen",
            field=models.FileField(
                upload_to="registros/resumenes/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
