# Generated by Django 4.1.1 on 2022-11-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0004_alter_presentacionregistro_presentacion_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='grado',
            field=models.CharField(choices=[('Cartel', 'Cartel')], max_length=30),
        ),
    ]
