# Generated by Django 4.1.1 on 2022-11-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0005_alter_author_grado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='grado',
            field=models.CharField(choices=[('Cartel', 'Cartel'), ('Ponencia', 'Ponencia')], max_length=30),
        ),
    ]
