# Generated by Django 4.1.1 on 2022-11-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0006_alter_author_grado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='grado',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Ingeniería', 'Ingeniería'), ('Licenciatura', 'Licenciatura'), ('Doctorado', 'Doctorado'), ('Maestría', 'Maestría')], max_length=30),
        ),
        migrations.AlterField(
            model_name='presentacionregistro',
            name='estatus',
            field=models.CharField(choices=[('Sin revisar', 'Sin revisar'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='presentacionregistro',
            name='modalidad',
            field=models.CharField(choices=[('Cartel', 'Cartel'), ('Ponencia', 'Ponencia')], max_length=30),
        ),
    ]
