# Generated by Django 4.1.1 on 2022-11-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0007_alter_author_grado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
